# Generated by Django 4.0.5 on 2022-06-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_email_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=4, max_length=20),
            preserve_default=False,
        ),
    ]
