# Generated by Django 4.0.6 on 2022-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mpesa_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
