# Generated by Django 4.0.2 on 2022-03-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=500)),
                ('zipped', models.BooleanField(default=None)),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='product_images')),
            ],
        ),
    ]
