# Generated by Django 4.0.3 on 2022-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='zipped',
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
