# Generated by Django 4.0.4 on 2022-04-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_product_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
    ]
