# Generated by Django 4.0.6 on 2022-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='who_needs',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
