# Generated by Django 4.0.6 on 2022-09-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_alter_product_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='many_files',
        ),
        migrations.AddField(
            model_name='packages',
            name='packages',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='frontend.product'),
        ),
    ]
