# Generated by Django 4.0.6 on 2022-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_rename_file_packages_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_field',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
